default_platform(:ios)

platform :ios do

  # App Store Connect API Key 설정 (모든 lane에서 공유)
  before_all do
    app_store_connect_api_key(
      key_id: "7X4FZ564SR",
      issuer_id: "c5d0448a-84ed-476a-a74a-d4cc0cc84bd3",
      key_filepath: "fastlane/AuthKey_7X4FZ564SR.p8"
    )
  end

  # TestFlight 업로드
  desc "TestFlight에 빌드 업로드"
  lane :testflight do
    increment_build_number
    build_app(
      scheme: "Keychy",
      export_method: "app-store",
      clean: true,
      export_options: {
        signingStyle: "manual",
        signingCertificate: "Apple Distribution",
        provisioningProfiles: {
          "com.KeychyOfficial.app" => "KeychyApp Distribution",
          "com.KeychyOfficial.app.WidgetKeychy" => "KeychyApp Widget Distribution"
        }
      }
    )
    upload_to_testflight(
      skip_waiting_for_build_processing: true
    )
  end

  # App Store 업로드
  desc "App Store에 빌드 업로드"
  lane :appstore do
    increment_build_number
    build_app(
      scheme: "Keychy",
      export_method: "app-store",
      clean: true,
      export_options: {
        signingStyle: "manual",
        signingCertificate: "Apple Distribution",
        provisioningProfiles: {
          "com.KeychyOfficial.app" => "KeychyApp Distribution",
          "com.KeychyOfficial.app.WidgetKeychy" => "KeychyApp Widget Distribution"
        }
      }
    )
    upload_to_app_store(
      skip_metadata: true,
      skip_screenshots: true,
      precheck_include_in_app_purchases: false
    )
  end

end
